name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - Automatización

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Install Tidy for HTML validation
        run: |
          sudo apt update
          sudo apt install -y tidy

      - name: Validate HTML
        run: find . -name "*.html" -exec tidy -e {} \;

      - name: Validate CSS
        run: npx stylelint "**/*.css"

      - name: Run Stylelint
        run: npx --no-install stylelint "**/*.css"
      

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./